services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
      - storage:/var/www/html/storage
      - cache:/var/www/html/bootstrap/cache
    command: [ "bash", "-lc", "./docker/app/init-perms.sh && php-fpm -F" ]
    depends_on:
      - db

  web:
    image: nginx:stable
    container_name: laravel-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  vendor:
  storage:
  cache:
